### ISSUE TITLE
Preserve changed LilyPond source when PDFs do not change

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/ide#1]
Problem:

When you illustrate a segment, when that segment already has an illustration, if the changes you've made have no impact on the graphic output -- e.g., you've added comments to the source showing which container is at what measure number -- the new source will be discarded simply because the pdfs compare the same.

**Comment by trevorbaca** [comment]
Done 2015-09-17.

**Comment by josiah-wolf-oberholtzer** [comment]
Yay! This one was a real sore point for me!
