### ISSUE TITLE
Consider removing materials (!) in favor of tools

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/ide#135]
The distinction between materials packages and the contents of the `tools/` directory has never been completely clear.

It may be possible to remove `materials/` directories from score packages entirely, relying entirely on the content of the `tools/` directory instead.

**Comment by josiah-wolf-oberholtzer** [comment]
would class files in `tools/` then be wrapped in their own subpackages? would the layout be heterogenous (python modules and material subpackages side-by-side)?

**Comment by trevorbaca** [comment]
Great questions. Ok, lessee ...

My tools packages are currently "two-way" heterogenous, kinda like this:
```

Spiel der Dornen (2016) - tools directory

   1: __init__.py
   2: DesignMaker.py
   3: FigureAccumulator.py
   4: ScoreTemplate.py
   5: make_anchor_figure_maker.py
   6: make_default_figure_maker.py
   7: make_delicatissimo_figure_maker.py
   8: make_design_1.py
   9: make_design_2.py
  10: make_design_3.py
  11: make_monad_figure_maker.py
  12: make_passepied_figure_maker.py
  13: make_ritardando_figure_maker.py
  14: make_running_figure_maker.py
  15: make_thorn_figure_maker_1.py

      copy (cp)
      new (new)
      remove (rm)
      rename (ren)

> 
```
So the `tools/` directories have both classfiles and also 'functionfiles'. (Usually now more 'functionfiles' than classfiles, actually. Which has evolved to be different than how we started out using the `tools/` directories.) The nice thing about the "two-way" heterogeneity is that it mirrors the contents of the Abjad packages exactly: classfiles and functionfiles are both allowed. (Also to note: the files in my `tools/` directories are all just plain ole vanilla files. None of 'em are packages.)

Your other question about the status of materials packages is definitely the harder one to answer. I'm still using `materials/` directories the way that we designed them years back:
```
Spiel der Dornen (2016) - materials directory

   1: __abbreviations__.py
   2: __init__.py
   3: __metadata__.py
   4: __views__.py
   5: blue pitch classes
   6: bright green pitch classes
   7: green pitch classes
   8: instruments
   9: magenta pitch classes
  10: tempi

      copy (cp)
      new (new)
      remove (rm)
      rename (ren)

> 
```
But as my usage has evolved I notice myself populating the `materials/` directories less and less, and populating the `tools/` directories more and more.

Of course it's always ok to load balance between the two directories for more-or-less cosmetic reasons. But a substantive reason has emerged, and it has to do with the way that imports work. (Of course! ;) There's an example available in the collateral shown above in the IDE screenshots. But of course it's tricky to narrate effectively. I'll give it a go, hoping I can describe it correctly:

Ok first recall that the initializer for every score package imports the `tools` package first and only after that imports the `materials` package:
```
# -*- coding: utf-8 -*-
from dornen import tools
from dornen import materials
from dornen import segments
```
In itself this is fine and has been working for everything up until now. But now walk through the following context with me:

The `DesignMaker` class (shown above in the `tools/` directory) makes designs. The primary input required are the "colored" pitch-classes (blue, bright green, green, magenta) house in the `materials/` directory. Even though `tools` are interpreted before `materials` this is no problem because the `DesignMaker` just late-imports the four different pitch-class materials.

So far so good.

But the import problem arises when I try to define a material package for one of the designs (that result from calling the `DesignMaker`). No such design material package is show in the material directory screenshot above (because of the import error that results when trying to define such a package). But imagine trying to define such a package like this (in the material definition.py file):
```
# -*- coding: utf-8 -*-
from dornen.tools.DesignMaker import DesignMaker

design_1 = DesignMaker()
```
What happens here? What happens is that `DesignMaker.__call__()` attempts to import the "colored" pitch-class material packages (mentioned above), but gets something like this:
```
  File "/Users/trevorbaca/Scores/dornen/dornen/tools/DesignMaker.py", line 25, in __init__
    dornen.materials.blue_pitch_classes
AttributeError: 'module' object has no attribute 'materials'
```
Why does this happen? Basically because the design assumption (evidenced by the structure of the score package initializers, as shown above) has been that tools can be used to create materials (hence `tools` being imported before `materials`) but not that **materials might be used in the definition or execution of tools**.

Did any of that make sense? Again, apologies for the twisted presentation of the problem: import circles are always such a pain to explain linearly.

Ok, so assuming that kinda made sense, my reflections are these. First, this isn't the end of the world, as we can see from the existing solution (shown above) that uses `make_design_1()` factory functions in place of `materials.design_1` materials packages. (So this isn't stopping actual composing from getting done.) But, second, maybe what this is pointing to is that the distinction between tools and materials isn't motivated after all. The primary reason I created the concept of a materials package in the first place (all the way back a couple of years ago) was to allow for the illustration of a material package as a PDF. And this used to be really important. Why? Because custom classes and functions housed inside a score package **weren't** being documented by Sphinx. But now custom classes and functions are being documented by Sphinx. And this means that illustration is now 100% doable in the usual way shown in the Abjad mainline, just by adding usage examples to docstrings.

So that's where my thinking has arrived. The TL;DR is that import errors suggest that the distinction between `tools` and `materials` may only have been motivated by the desire for the illustration of materials. Which is now accomplishable in the same way as our doc building system ;-)

Be curious to hear your thoughts. Note that if collapsing `materials/` into `tools/` does seem like a cleaner long-term idea, it will still be quite a while before I'll actually make the change. Because it would mean refactoring all our existing materials packages as classes or functions housed in our `tools/` directories. But it probably would be conceptually considerably cleaner: our score packages come very much closer to mirroring the structure of the Abjad mainline, and imports between files in the `tools/` directories just work the same way as in Abjad.

**Comment by josiah-wolf-oberholtzer** [comment]
Circular imports are always a problem.

Anyways, I'm not using any docs for my scores. Score output in Sphinx is not appealing due to the rasterization, and the feedback loop is faster to just illustrate them in place. And I'm definitely illustrating all of my materials all the time as chunks of full score in PDF, with real-world page-layout concerns.

I guess I'm not convinced yet.

**Comment by josiah-wolf-oberholtzer** [comment]
I also don't know that we have to choose one way or the other. Don't want to compose with materials packages? You don't have to use them. Don't want to compose with material-generating functions in your tools package? You don't have to do that either.

I think we can happily sit on this discussion for as long as necessary. Wait a few scores. We may not need to take action. Remember that you and I are really the only two people working this way at the moment. If / when others start playing with this project layout, we may see that there's some consensus. And, quite probably, we may see that that consensus doesn't apply to all aspects of the system. Time and usage will tell.

**Comment by trevorbaca** [comment]
Yes, I'm fine with all this. Waiting is definitely a great idea. But notice that, so far, we haven't addressed the one substantive reason motivating getting rid of materials packages: it's simply not possible (given the current set up) to build certain types of material packages.

So just keep this in mind as you marinade ;) some types of materials packages (that maybe you haven't gotten to yet) simply are not possible to construct. But all tools classfiles and function files are possible to construct.

**Comment by josiah-wolf-oberholtzer** [comment]
Wait, what kind of material is not possible to construct? I'm still not
clear on that. I successfully import materials and tools back and forth,
and import materials into other materials. What's the issue?

**Comment by trevorbaca** [comment]
That was the purpose to the (long!) description in the primary post!

**Comment by josiah-wolf-oberholtzer** [comment]
I'm not able to reproduce! :))))

Let's try a minimal example.

So you have a new score - `example` - with:
- a material `markup` subpackage, whose definition just has a `Markup` instance in it
- a tool module `FooMaker.py` defining a `FooMaker` class:
    - with `from example.materials import markup` in its initializer
- and a `foo_maker` material subpackage
    - which imports `from example.tools import FooMaker`
    - and defines `foo_maker = FooMaker()`

You're saying that if you fire up an interpreter and try `import example` it'll blow up?

Try the attached score package:

[example.zip](https://github.com/Abjad/ide/files/340293/example.zip)

I don't seem to have any import weirdness here, importing back and forth between tools and materials. Please tinker with it and send it back via a comment if you can make it blow up. I just need a concrete example of the trouble.

**Comment by trevorbaca** [comment]
Awesome! Thanks so much for delving into this one. Super kind ;)

Will tinker and send back over, (though probably tomorrow!).

On Wed, Jun 29, 2016 at 5:04 PM, Josiah Wolf Oberholtzer <
notifications@github.com> wrote:

> I'm not able to reproduce! :))))
>
> Let's try a minimal example.
>
> So you have a new score - example - with:
>
>    - a material markup subpackage, whose definition just has a Markup
>    instance in it
>    - a tool module FooMaker.py defining a FooMaker class:
>       - with from example.materials import markup in its initializer
>    - and a foo_maker material subpackage
>       - which imports from example.tools import FooMaker
>       - and defines foo_maker = FooMaker()
>
> You're saying that if you fire up an interpreter and try import example
> it'll blow up?
>
> Try the attached score package:
>
> example.zip <https://github.com/Abjad/ide/files/340293/example.zip>
>
> I don't seem to have any import weirdness here, importing back and forth
> between tools and materials. Please tinker with it and send it back via a
> comment if you can make it blow up. I just need a concrete example of the
> trouble.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Abjad/ide/issues/135#issuecomment-229503181>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AFiSvdQKtkLeJ9jktJTqSoE6Vrf7ZO7eks5qQuvbgaJpZM4JAX2A>
> .
>



-- 
Trevor Bača
www.trevorbaca.com
soundcloud.com/trevorbaca

**Comment by josiah-wolf-oberholtzer** [comment]
Yeah, thanks for any time you can spare looking at this. I'm sure we can make the imports work for everyone. 😆
