### ISSUE TITLE
Preserve whitespace in exception messages

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [Abjad/ide#2]
The IDE should preserve whitespace in displayed exceptions and tracebacks.

**Comment by trevorbaca** [comment]
Hey Josiah, do you have an example of a place where we're printing an exception or traceback to the user? Happy to spend a bit of time debugging.

**Comment by josiah-wolf-oberholtzer** [comment]
Make a material package.

Give it the following contents:

```
if True:
    if True:
        if True:
            raise Exception
```

Save it and run (dc). No matter how many `if True:` suites you add or
remove, the traceback is always flattened to the left.

I'm fairly certain the stripping is happening in IOManager.interpret_file()
and IOManager._read_from_pipe().

On Tue, Jul 14, 2015 at 12:05 PM, Trevor Bača <notifications@github.com>
wrote:

> Hey Josiah, do you have an example of a place where we're printing an
> exception or traceback to the user? Happy to spend a bit of time debugging.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Abjad/ide/issues/2#issuecomment-121343940>.
>



-- 
Josiah Wolf Oberholtzer, PhD
http://josiahwolfoberholtzer.com

**Comment by trevorbaca** [comment]
Ok great. Looking into it.

**Comment by trevorbaca** [comment]
Done 2015-09-22.
