### ISSUE TITLE
maybe little getting started guide?

### ISSUE THREAD

**Issue by smoge** [Abjad/ide#252]
I found this project very interesting, but it is not clear what kind of routine is involved. It would be nice if you could include a little guide to basic features and common work routines.

**Comment by trevorbaca** [comment]
Hi Bernardo :)

Yes, a getting-started guide would be great! Probably another year longer, though: the IDE encapsulates everything I've learned about the filesystem layout of (sometimes very large) scores in Abjad (and LilyPond). That research is ongoing; I think probably another year before I'm ready to commit the patterns to documentation!
