### ISSUE TITLE
Display package files in materials directory

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/ide#58]
CURRENT:
```
Score (2015) - materials directory

      first_material
      second_material
      third_material

      materials - copy (cp)
      materials - new (new)
      materials - remove (rm)
      materials - rename (ren)
```

BETTER:
```
Score (2015) - materials directory

      __abbreviations__.py
      __init__.py
      __metadata__.py

      first_material
      second_material
      third_material

      materials - copy (cp)
      materials - new (new)
      materials - remove (rm)
      materials - rename (ren)
```

**Comment by josiah-wolf-oberholtzer** [comment]
+1

On Sat, Jul 18, 2015 at 1:55 PM, Trevor Bača <notifications@github.com>
wrote:

> CURRENT:
>
> Score (2015) - materials directory
>
>       first_material
>       second_material
>       third_material
>
>       materials - copy (cp)
>       materials - new (new)
>       materials - remove (rm)
>       materials - rename (ren)
>
> BETTER:
>
> Score (2015) - materials directory
>
>       __abbreviations__.py
>       __init__.py
>       __metadata__.py
>
>       first_material
>       second_material
>       third_material
>
>       materials - copy (cp)
>       materials - new (new)
>       materials - remove (rm)
>       materials - rename (ren)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Abjad/ide/issues/58>.
>



-- 
Josiah Wolf Oberholtzer, PhD
http://josiahwolfoberholtzer.com
